### PR TITLE
Ongoing unbranding of Hometown [WIP]

### PR DESCRIPTION
**Pull request by emmawinston**
@dariusk has suggested that Hometown should be more of a ‘blank slate’ for instance admins than Mastodon is currently. To this end, I am gradually going through the language files to replace mentions of Mastodon with either generic labels or the name of the instance, where appropriate. Where useful, for example in copy which discusses native mobile apps, ‘Mastodon’ is left intact. This more specific labelling should hopefully also clarify the structure of the fediverse a little to new users.

I am additionally replacing the term ‘toot’ with ‘post’.

I am also removing the cartoon elephants where possible. Some, like those in the onboarding tutorial, will ultimately need to either be left in or replaced with other images.

So far I am altering text only in English language files, but will try to transfer my wording to other language files when further along in the process.

### CODE REVIEW

**Comment by dariusk** [comment]
This looks soooooo good!

I did find some hidden elephants and one text alignment bug.

At the url `http://localhost:3000/auth/sign_in` when you are not logged in, you see a Mastodon logo:

image

At `http://localhost:3000/about`, when you are not logged in, you see Mastodon branding in the lower right:

image

If you go to a url like `http://localhost:3000/poop` you will see a frustrated elephant:

image

There's a CSS problem with text layout of the instance name in the public feed (related to [this commit](https://github.com/hometown-fork/hometown/pull/19/commits/e6c1b3917a221943b3f4f050ff2d222ac486013d), found at `http://localhost:3000/public` (see upper left):

image

**Review by dariusk — CHANGES_REQUESTED** [review]
Requesting changes as mentioned above!

**Comment by emmawinston** [comment]
I will aim to fix the login logo and the alignment bug later today. My sense is that the login logo is better replaced with the name of the instance, so if you're happy with that that's what I'll do. 

I do, I think, need to ask for your views on what to do with the remaining elephants (the tutorial and every instance of a hero image [the landscape aspect ratio ones with the trumpet elephants] are the ones my original PR alluded to when I said they 'will ultimately need to either be left in or replaced with other images' - the keysmash elephant could be removed entirely but I'm not sure if this is the best approach or not).

The only art I have from you for Hometown is the potted plant. Its aspect ratio looks absolutely wrong in the hero boxes, and it feels (to me) inappropriate to simply replace the tutorial and keysmash elephants with it - it doesn't really make any sense, as a single image, to accompany either a tutorial or the 'something went wrong' page. 

We actually have, at least as I see it, a few options here. 

- Make the tutorial/hero boxes smaller, and remove the tutorial/hero/keysmash images entirely 
- Commission alternative art from someone
- Have _me_ attempt to draw some alternative art (I think this is probably the worst option!)
- Find art to fit these spaces from the Noun Project (or somewhere else)
- Leave as-is

I lean towards removing the image from the hero boxes on public profile pages, but I do think the signup page needs some art really and think it would be a shame to remove the hero image from there completely - I think it looks pretty bleak and dated without anything there - so (IMO) it would be good to find a replacement for it there specifically. I also worry that the tutorial might feel duller or less readable without art. The keysmash elephant I'm unsure about.

**Comment by dariusk** [comment]
Your suggestions sound good. Let's

* replace the login logo with the name of the instance
* remove the image from the hero boxes from the public profile pages
* leave the large-format art in the registration/keysmash/onboarding pages as-is for now, with a future eye to commissioning alternative art

**Comment by emmawinston** [comment]
I've corrected all the above, as well as replacing the placeholder logo with the new one, as agreed away from Github. 

In general, when unsure, I've leaned towards removing rather than replacing images in places that can't be easily customised from the admin panel; I think it's better for things like the 404 page to be unbranded than to have the Hometown logo irrevocably on it.

As the current build stands, the only remaining Mastodon images should be the ones in the onboarding tutorial. 

Let me know if any further changes are needed!

**Review by dariusk — APPROVED** [review]

**Comment by dariusk** [comment]
Thanks!

**Pull request merged**
