### PR TITLE
Remove share intent button for local-only posts - closes #12

### LINKED ISSUE #12: Local-only toots should probably not be shareable
On certain mobile devices, Mastodon adds a share button on public statuses. However, as i understand, local-only toots are not really “public” and so should probably not have a share button attached.

For detailed statuses, the line controlling this is here (L178):

https://github.com/hometown-fork/hometown/blob/master/app/javascript/mastodon/features/status/components/action_bar.js#L178

And for ordinary (timeline) statuses, the line is here (L246):

https://github.com/hometown-fork/hometown/blob/master/app/javascript/mastodon/components/status_action_bar.js#L246

### PR DESCRIPTION
**Pull request by emmawinston**
Closes #12 - because the only mobile device I own is iOS I can't actually test this! Let me know if anything needs changing and I'll fix ASAP.

### CODE REVIEW

**Comment by hazel-bohon** [comment]
Is it possible to do this change in the Rails code so that mobile apps would be able to understand that the content cannot be shared?

**Comment by dariusk** [comment]
@zacherybohon That's a great question/suggestion. The problem with mobile apps right now is that the local-only posting has no way of "advertising" that it exists as a feature. Or if it does, it's not really documented! I will open a bug for that, which will probably involve contacting some app developers and asking if they are willing to support basic things like even rendering whether a post is local-only or not.

**Comment by dariusk** [comment]
@zacherybohon You can follow issue #6 for updates on this.

**Comment by dariusk** [comment]
Works great, thanks Emma!

**Pull request merged**
