### PR TITLE
Add max_toot_chars patch from glitch-soc

### LINKED ISSUE #38: Add admin panel field for maximum post length

### PR DESCRIPTION
**Pull request by sable-starflower**
This is a first step on https://github.com/hometown-fork/hometown/issues/38. I don't know much about how the UI panels work so I can't really help much there. But this does allow changing the max post length, and it consolidates all the logic in one place.

One thing I'm not sure about is that it stores the env value in a constant. For it to be updateable through the admin panel, I think it would need to be a class property somewhere, but I don't know enough about how the controllers are wired together to say where that should live. I figured I'd open this PR anyways in case it's at all helpful.

### CODE REVIEW

**Comment by ghost** [comment]
Hi,

Thanks for the proposition @sable-starflower, would you please fix the small conflict that appeared since you submitted this pull request?

I'm looking forward to merge this and fix #38

**Comment by sable-starflower** [comment]
fixed, thanks!

**Comment by ghost** [comment]
Thanks for your work, it's a nice backport of Glitch-soc implementation for this feature.

@dariusk would it be okay to merge this? it's gonna fix the issue you opened about this missing feature

If merged I'll document it like the other changes from Mastodon mainline.

**Comment by ghost** [comment]
i'm gonna prepare some documentation for this feature and i'll merge it as soon as it's ready

**Comment by dariusk** [comment]
Yes let's merge when documentation is up (if it is not yet up already!)

**Comment by ghost** [comment]
Documentation is up: https://github.com/hometown-fork/hometown/wiki/Custom-max-toot-characters

Merging!

**Pull request merged**
