### PR TITLE
Add support for Azure blob storage

### PR DESCRIPTION
**Pull request by mistydemeo**
This adds support for Azure blob storage using Paperclip, similar to what's supported for S3 and other backends. It makes use of the `paperclip-azure` plugin gem. As with S3, this is not loaded by default; it's only used if the proper environment variables are set.

I'm using my fork of paperclip-azure because it incorporates a few new features to make it feature-equivalent to S3 for Mastodon's purposes.

### CODE REVIEW

**Comment by mistydemeo** [comment]
(Sorry, hit enter too quickly. Filling out a description now.)

**Comment by mistydemeo** [comment]
@dariusk Any chance you'd be willing to consider merging this? I'm still trying to get it in upstream Mastodon, but it would simplify my tracking upstream changes from Hometown and Mastodon to have it merged somewhere.

**Comment by dariusk** [comment]
Merged! Sorry this took so long.

**Comment by mistydemeo** [comment]
Thank you!

**Pull request merged**
