### PR TITLE
Backport security changes from 4.0.6

### PR DESCRIPTION
**Pull request by mistydemeo**
This ports over security fixes from upstream Mastodon 4.0.6. Branch here: https://github.com/mastodon/mastodon/commits/stable-4.0

This doesn't port over non-security changes that were also in that release.

### CODE REVIEW

**Comment by dariusk** [comment]
Thank you!! I am in the middle of traveling but I hope to get a release out in about 6 hours from this.

**Comment by mistydemeo** [comment]
You're welcome! And thank you very much!

There's also #1316, which backports more commits from that release. This one's more targeted to specifically the security content, which might make it a safer release until you've got time to test.

**Comment by pronoiac** [comment]
I think, but am not positive, that the title should be 4.0.5. [Mastodon released 4.0.6 15 minutes ago](https://github.com/mastodon/mastodon/releases/tag/v4.0.6). It's another security release.

**Comment by mistydemeo** [comment]
Yes, the title was a typo.

**Pull request closed without merging**
